### ISSUE TITLE
Not getting the error "undefined variable"

### ISSUE THREAD

**Issue by sbnajardhane** [CoreyMSchafer/dotfiles#1]
Hi @CoreyMSchafer Help required.
I have followed the steps to setup anaconda sublime plugin. I have tried few things
```
for num in [1, 2, 3, 4]   # I got error syntax error here
    print n               # but i didn't get uindefined variable error here (i resolved the first error and then chacked)
```

Als, I have enabled the import validation
``` 
from user import get_usre_name # got error as "cannot import (as the method name was incorrect)"
```
But I didn't get any error, where I directly used the get_user_name method
```
user_name = get_user_name(user)` # I am assuming it should throw some error ' method is not imported'
```
I am new to the sublime text (using ST3) and python, so could you please help me out?
I have installed the anaconda plugin, copied the settings and added
`"python_interpreter": "/home/shubham/project/env/bin/python"`
Thanks.

**Comment by kaustubhpachpor** [comment]
Hi Shubham,

In the first syntax of nums,
Try this **print(num)** as, you can see, the build is unable to trace out what is the actual variable you have given to **n**
