### ISSUE TITLE
Issue reading drop-down Command Palette menu

### ISSUE THREAD

**Issue by frisbeedan** [CoreyMSchafer/dotfiles#2]
Hi Corey,

I was watching your YouTube video on setting up Sublime Text 3 for working with Python. Thanks so much for posting your videos, sharing information, and helping people like me to learn! It's much appreciated.

I tried adding your User Preferences code to ST3, and I ran into an issue: I can't see the Command Palette drop-down menu very well. I retried some previous settings I had, which I think used the default themes, and I could see the drop-down Command Palette just fine. Do you think this is simply an issue with using the Material Theme and the Predawn color scheme? Or do you think there could be something else at play? I'd like to use your settings, if possible, for getting started.

I think I've included a partial screenshot of my issue, which has some previous settings I had plus the material and predawn themes. You'll see that there really isn't a backdrop to the Command Palette drop-down...just the words.

If all else fails, maybe I can use most of your settings with different themes. Thanks for any thoughts/suggestions!

Daniel

![image](https://user-images.githubusercontent.com/45306749/52808467-f578c280-305b-11e9-995e-6166f2037704.png)

**Comment by frisbeedan** [comment]
Hi Corey,

My apologies. I think I had not installed the Material Theme package - my mistake! Please disregard my issue. Thanks again for all your work/teaching/sharing.

Daniel

**Comment by CoreyMSchafer** [comment]
Hey Daniel,

Sorry for such a late reply. I was trying to wrap up some videos. I'm glad
you got your issue resolved!

Corey
